// This file is auto-generated by @hey-api/openapi-ts

export type Body_login_login_access_token = {
    grant_type?: (string | null);
    username: string;
    password: string;
    scope?: string;
    client_id?: (string | null);
    client_secret?: (string | null);
};

export type CompetitionPublic = {
    date_from?: (string | null);
    date_to?: (string | null);
    name?: (string | null);
    rank_name?: (string | null);
    competition_code?: (string | null);
    id_country?: (number | null);
    city?: (string | null);
    timezone?: (string | null);
    id: number;
};

export type CompetitionsPublic = {
    data: Array<CompetitionPublic>;
    count: number;
};

export type ContestPublic = {
    id_competition?: (number | null);
    id_judoka_blue?: (number | null);
    id_judoka_white?: (number | null);
    id_winner?: (number | null);
    is_finished?: (number | null);
    duration?: (string | null);
    ippon_w?: (number | null);
    waza_w?: (number | null);
    yuko_w?: (number | null);
    penalty_w?: (number | null);
    hsk_w?: (number | null);
    ippon_b?: (number | null);
    waza_b?: (number | null);
    yuko_b?: (number | null);
    penalty_b?: (number | null);
    hsk_b?: (number | null);
    round?: (number | null);
    round_code?: (string | null);
    round_name?: (string | null);
    type?: (number | null);
    gs?: (number | null);
    bye?: (number | null);
    fight_no?: (number | null);
    weight?: (string | null);
    id_weight?: (number | null);
    fight_duration?: (number | null);
    rank_name?: (string | null);
    rating_change_w?: (number | null);
    rating_change_b?: (number | null);
    id: number;
};

export type ContestsPublic = {
    data: Array<ContestPublic>;
    count: number;
};

export type CountriesPublic = {
    data: Array<CountryPublic>;
    count: number;
};

export type CountryPublic = {
    name?: (string | null);
    ioc?: (string | null);
    file_flag?: (string | null);
    id: number;
};

export type DataSyncPublic = {
    sync_type: string;
    status: string;
    started_at: string;
    completed_at?: (string | null);
    records_processed?: number;
    records_created?: number;
    records_updated?: number;
    error_message?: (string | null);
    created_by?: (string | null);
    id: string;
};

export type DataSyncsPublic = {
    data: Array<DataSyncPublic>;
    count: number;
};

export type HTTPValidationError = {
    detail?: Array<ValidationError>;
};

export type JudokaPublic = {
    family_name?: (string | null);
    given_name?: (string | null);
    gender?: (string | null);
    judoka_picture?: (string | null);
    dob_year?: (number | null);
    id_country?: (number | null);
    id: number;
};

export type JudokasPublic = {
    data: Array<JudokaPublic>;
    count: number;
};

export type Message = {
    message: string;
};

export type NewPassword = {
    token: string;
    new_password: string;
};

export type RatingChangePublic = {
    id_judoka?: (number | null);
    id_contest?: (number | null);
    id_opponent?: (number | null);
    opponent_rating_at_match?: (number | null);
    rating_change?: (number | null);
    opponent_rating_change?: (number | null);
    id: number;
};

export type RatingChangesPublic = {
    data: Array<RatingChangePublic>;
    count: number;
};

export type RatingFormulaCreate = {
    name: string;
    description?: (string | null);
    is_active?: boolean;
};

export type RatingFormulaPublic = {
    name: string;
    description?: (string | null);
    is_active?: boolean;
    id: string;
};

export type RatingFormulasPublic = {
    data: Array<RatingFormulaPublic>;
    count: number;
};

export type RatingFormulaUpdate = {
    name?: (string | null);
    description?: (string | null);
    is_active?: (boolean | null);
};

export type RatingPublic = {
    id_judoka?: (number | null);
    id_weight?: (number | null);
    weight?: (string | null);
    formula_id?: (string | null);
    rating_value?: (number | null);
    id: number;
    judoka_family_name?: (string | null);
    judoka_given_name?: (string | null);
};

export type RatingsPublic = {
    data: Array<RatingPublic>;
    count: number;
};

export type Token = {
    access_token: string;
    token_type?: string;
};

export type UpdatePassword = {
    current_password: string;
    new_password: string;
};

export type UserCreate = {
    email: string;
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    password: string;
};

export type UserPublic = {
    email: string;
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    id: string;
};

export type UserRegister = {
    email: string;
    password: string;
    full_name?: (string | null);
};

export type UsersPublic = {
    data: Array<UserPublic>;
    count: number;
};

export type UserUpdate = {
    email?: (string | null);
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    password?: (string | null);
};

export type UserUpdateMe = {
    full_name?: (string | null);
    email?: (string | null);
};

export type ValidationError = {
    loc: Array<(string | number)>;
    msg: string;
    type: string;
};

export type CompetitionsReadCompetitionsData = {
    idCountry?: (number | null);
    limit?: number;
    skip?: number;
};

export type CompetitionsReadCompetitionsResponse = (CompetitionsPublic);

export type CompetitionsReadCompetitionData = {
    competitionId: number;
};

export type CompetitionsReadCompetitionResponse = (CompetitionPublic);

export type CompetitionsReadCompetitionContestsData = {
    competitionId: number;
    limit?: number;
    skip?: number;
};

export type CompetitionsReadCompetitionContestsResponse = (unknown);

export type ContestsReadContestsData = {
    competitionId?: (number | null);
    judokaId?: (number | null);
    limit?: number;
    skip?: number;
};

export type ContestsReadContestsResponse = (ContestsPublic);

export type ContestsReadContestData = {
    contestId: number;
};

export type ContestsReadContestResponse = (ContestPublic);

export type CountriesReadCountriesData = {
    limit?: number;
    skip?: number;
};

export type CountriesReadCountriesResponse = (CountriesPublic);

export type CountriesReadCountryData = {
    countryId: number;
};

export type CountriesReadCountryResponse = (CountryPublic);

export type JudokasReadJudokasData = {
    idCountry?: (number | null);
    limit?: number;
    skip?: number;
};

export type JudokasReadJudokasResponse = (JudokasPublic);

export type JudokasReadJudokaData = {
    judokaId: number;
};

export type JudokasReadJudokaResponse = (JudokaPublic);

export type JudokasReadJudokaContestsData = {
    judokaId: number;
    limit?: number;
    skip?: number;
};

export type JudokasReadJudokaContestsResponse = (unknown);

export type JudokasReadJudokaRatingsData = {
    judokaId: number;
};

export type JudokasReadJudokaRatingsResponse = (unknown);

export type LoginLoginAccessTokenData = {
    formData: Body_login_login_access_token;
};

export type LoginLoginAccessTokenResponse = (Token);

export type LoginTestTokenResponse = (UserPublic);

export type LoginRecoverPasswordData = {
    email: string;
};

export type LoginRecoverPasswordResponse = (Message);

export type LoginResetPasswordData = {
    requestBody: NewPassword;
};

export type LoginResetPasswordResponse = (Message);

export type LoginRecoverPasswordHtmlContentData = {
    email: string;
};

export type LoginRecoverPasswordHtmlContentResponse = (string);

export type RatingChangesReadRatingChangesData = {
    contestId?: (number | null);
    judokaId?: (number | null);
    limit?: number;
    skip?: number;
};

export type RatingChangesReadRatingChangesResponse = (RatingChangesPublic);

export type RatingFormulasReadRatingFormulasData = {
    isActive?: (boolean | null);
    limit?: number;
    skip?: number;
};

export type RatingFormulasReadRatingFormulasResponse = (RatingFormulasPublic);

export type RatingFormulasCreateRatingFormulaData = {
    requestBody: RatingFormulaCreate;
};

export type RatingFormulasCreateRatingFormulaResponse = (RatingFormulaPublic);

export type RatingFormulasReadRatingFormulaData = {
    formulaId: string;
};

export type RatingFormulasReadRatingFormulaResponse = (RatingFormulaPublic);

export type RatingFormulasUpdateRatingFormulaData = {
    formulaId: string;
    requestBody: RatingFormulaUpdate;
};

export type RatingFormulasUpdateRatingFormulaResponse = (RatingFormulaPublic);

export type RatingFormulasDeleteRatingFormulaData = {
    formulaId: string;
};

export type RatingFormulasDeleteRatingFormulaResponse = (unknown);

export type RatingsReadRatingsData = {
    formulaId?: (string | null);
    judokaId?: (number | null);
    limit?: number;
    ratingMin?: (number | null);
    skip?: number;
    surname?: (string | null);
    weight?: (string | null);
};

export type RatingsReadRatingsResponse = (RatingsPublic);

export type RatingsReadLeaderboardData = {
    formulaId: string;
    limit?: number;
    skip?: number;
};

export type RatingsReadLeaderboardResponse = (unknown);

export type RatingsReadJudokaRatingData = {
    formulaId: string;
    judokaId: number;
};

export type RatingsReadJudokaRatingResponse = (RatingPublic);

export type RatingsReadRatingHistoryData = {
    formulaId: string;
    judokaId: number;
    limit?: number;
    skip?: number;
};

export type RatingsReadRatingHistoryResponse = (unknown);

export type SyncTriggerSyncResponse = (DataSyncPublic);

export type SyncReadSyncHistoryData = {
    limit?: number;
    skip?: number;
    status?: (string | null);
};

export type SyncReadSyncHistoryResponse = (DataSyncsPublic);

export type SyncReadSyncData = {
    syncId: string;
};

export type SyncReadSyncResponse = (DataSyncPublic);

export type UsersReadUsersData = {
    limit?: number;
    skip?: number;
};

export type UsersReadUsersResponse = (UsersPublic);

export type UsersCreateUserData = {
    requestBody: UserCreate;
};

export type UsersCreateUserResponse = (UserPublic);

export type UsersReadUserMeResponse = (UserPublic);

export type UsersDeleteUserMeResponse = (Message);

export type UsersUpdateUserMeData = {
    requestBody: UserUpdateMe;
};

export type UsersUpdateUserMeResponse = (UserPublic);

export type UsersUpdatePasswordMeData = {
    requestBody: UpdatePassword;
};

export type UsersUpdatePasswordMeResponse = (Message);

export type UsersRegisterUserData = {
    requestBody: UserRegister;
};

export type UsersRegisterUserResponse = (UserPublic);

export type UsersReadUserByIdData = {
    userId: string;
};

export type UsersReadUserByIdResponse = (UserPublic);

export type UsersUpdateUserData = {
    requestBody: UserUpdate;
    userId: string;
};

export type UsersUpdateUserResponse = (UserPublic);

export type UsersDeleteUserData = {
    userId: string;
};

export type UsersDeleteUserResponse = (Message);

export type UtilsTestEmailData = {
    emailTo: string;
};

export type UtilsTestEmailResponse = (Message);

export type UtilsHealthCheckResponse = (boolean);