/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RecoverPasswordRouteImport } from './routes/recover-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LayoutRouteImport } from './routes/_layout'
import { Route as LayoutIndexRouteImport } from './routes/_layout/index'
import { Route as LayoutSyncsRouteImport } from './routes/_layout/syncs'
import { Route as LayoutSettingsRouteImport } from './routes/_layout/settings'
import { Route as LayoutRatingsRouteImport } from './routes/_layout/ratings'
import { Route as LayoutRatingFormulasRouteImport } from './routes/_layout/rating-formulas'
import { Route as LayoutRatingChangesRouteImport } from './routes/_layout/rating-changes'
import { Route as LayoutJudokasRouteImport } from './routes/_layout/judokas'
import { Route as LayoutCountriesRouteImport } from './routes/_layout/countries'
import { Route as LayoutContestsRouteImport } from './routes/_layout/contests'
import { Route as LayoutCompetitionsRouteImport } from './routes/_layout/competitions'
import { Route as LayoutCommandsRouteImport } from './routes/_layout/commands'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RecoverPasswordRoute = RecoverPasswordRouteImport.update({
  id: '/recover-password',
  path: '/recover-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutRoute = LayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutIndexRoute = LayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutSyncsRoute = LayoutSyncsRouteImport.update({
  id: '/syncs',
  path: '/syncs',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutSettingsRoute = LayoutSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutRatingsRoute = LayoutRatingsRouteImport.update({
  id: '/ratings',
  path: '/ratings',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutRatingFormulasRoute = LayoutRatingFormulasRouteImport.update({
  id: '/rating-formulas',
  path: '/rating-formulas',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutRatingChangesRoute = LayoutRatingChangesRouteImport.update({
  id: '/rating-changes',
  path: '/rating-changes',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutJudokasRoute = LayoutJudokasRouteImport.update({
  id: '/judokas',
  path: '/judokas',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutCountriesRoute = LayoutCountriesRouteImport.update({
  id: '/countries',
  path: '/countries',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutContestsRoute = LayoutContestsRouteImport.update({
  id: '/contests',
  path: '/contests',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutCompetitionsRoute = LayoutCompetitionsRouteImport.update({
  id: '/competitions',
  path: '/competitions',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutCommandsRoute = LayoutCommandsRouteImport.update({
  id: '/commands',
  path: '/commands',
  getParentRoute: () => LayoutRoute,
} as any)

export interface FileRoutesByFullPath {
  '/login': typeof LoginRoute
  '/recover-password': typeof RecoverPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/commands': typeof LayoutCommandsRoute
  '/competitions': typeof LayoutCompetitionsRoute
  '/contests': typeof LayoutContestsRoute
  '/countries': typeof LayoutCountriesRoute
  '/judokas': typeof LayoutJudokasRoute
  '/rating-changes': typeof LayoutRatingChangesRoute
  '/rating-formulas': typeof LayoutRatingFormulasRoute
  '/ratings': typeof LayoutRatingsRoute
  '/settings': typeof LayoutSettingsRoute
  '/syncs': typeof LayoutSyncsRoute
  '/': typeof LayoutIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/recover-password': typeof RecoverPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/commands': typeof LayoutCommandsRoute
  '/competitions': typeof LayoutCompetitionsRoute
  '/contests': typeof LayoutContestsRoute
  '/countries': typeof LayoutCountriesRoute
  '/judokas': typeof LayoutJudokasRoute
  '/rating-changes': typeof LayoutRatingChangesRoute
  '/rating-formulas': typeof LayoutRatingFormulasRoute
  '/ratings': typeof LayoutRatingsRoute
  '/settings': typeof LayoutSettingsRoute
  '/syncs': typeof LayoutSyncsRoute
  '/': typeof LayoutIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_layout': typeof LayoutRouteWithChildren
  '/login': typeof LoginRoute
  '/recover-password': typeof RecoverPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/_layout/commands': typeof LayoutCommandsRoute
  '/_layout/competitions': typeof LayoutCompetitionsRoute
  '/_layout/contests': typeof LayoutContestsRoute
  '/_layout/countries': typeof LayoutCountriesRoute
  '/_layout/judokas': typeof LayoutJudokasRoute
  '/_layout/rating-changes': typeof LayoutRatingChangesRoute
  '/_layout/rating-formulas': typeof LayoutRatingFormulasRoute
  '/_layout/ratings': typeof LayoutRatingsRoute
  '/_layout/settings': typeof LayoutSettingsRoute
  '/_layout/syncs': typeof LayoutSyncsRoute
  '/_layout/': typeof LayoutIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/login'
    | '/recover-password'
    | '/reset-password'
    | '/signup'
    | '/commands'
    | '/competitions'
    | '/contests'
    | '/countries'
    | '/judokas'
    | '/rating-changes'
    | '/rating-formulas'
    | '/ratings'
    | '/settings'
    | '/syncs'
    | '/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/recover-password'
    | '/reset-password'
    | '/signup'
    | '/commands'
    | '/competitions'
    | '/contests'
    | '/countries'
    | '/judokas'
    | '/rating-changes'
    | '/rating-formulas'
    | '/ratings'
    | '/settings'
    | '/syncs'
    | '/'
  id:
    | '__root__'
    | '/_layout'
    | '/login'
    | '/recover-password'
    | '/reset-password'
    | '/signup'
    | '/_layout/commands'
    | '/_layout/competitions'
    | '/_layout/contests'
    | '/_layout/countries'
    | '/_layout/judokas'
    | '/_layout/rating-changes'
    | '/_layout/rating-formulas'
    | '/_layout/ratings'
    | '/_layout/settings'
    | '/_layout/syncs'
    | '/_layout/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  LayoutRoute: typeof LayoutRouteWithChildren
  LoginRoute: typeof LoginRoute
  RecoverPasswordRoute: typeof RecoverPasswordRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SignupRoute: typeof SignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recover-password': {
      id: '/recover-password'
      path: '/recover-password'
      fullPath: '/recover-password'
      preLoaderRoute: typeof RecoverPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof LayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/': {
      id: '/_layout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof LayoutIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/syncs': {
      id: '/_layout/syncs'
      path: '/syncs'
      fullPath: '/syncs'
      preLoaderRoute: typeof LayoutSyncsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/settings': {
      id: '/_layout/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof LayoutSettingsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/ratings': {
      id: '/_layout/ratings'
      path: '/ratings'
      fullPath: '/ratings'
      preLoaderRoute: typeof LayoutRatingsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/rating-formulas': {
      id: '/_layout/rating-formulas'
      path: '/rating-formulas'
      fullPath: '/rating-formulas'
      preLoaderRoute: typeof LayoutRatingFormulasRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/rating-changes': {
      id: '/_layout/rating-changes'
      path: '/rating-changes'
      fullPath: '/rating-changes'
      preLoaderRoute: typeof LayoutRatingChangesRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/judokas': {
      id: '/_layout/judokas'
      path: '/judokas'
      fullPath: '/judokas'
      preLoaderRoute: typeof LayoutJudokasRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/countries': {
      id: '/_layout/countries'
      path: '/countries'
      fullPath: '/countries'
      preLoaderRoute: typeof LayoutCountriesRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/contests': {
      id: '/_layout/contests'
      path: '/contests'
      fullPath: '/contests'
      preLoaderRoute: typeof LayoutContestsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/competitions': {
      id: '/_layout/competitions'
      path: '/competitions'
      fullPath: '/competitions'
      preLoaderRoute: typeof LayoutCompetitionsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/commands': {
      id: '/_layout/commands'
      path: '/commands'
      fullPath: '/commands'
      preLoaderRoute: typeof LayoutCommandsRouteImport
      parentRoute: typeof LayoutRoute
    }
  }
}

interface LayoutRouteChildren {
  LayoutCommandsRoute: typeof LayoutCommandsRoute
  LayoutCompetitionsRoute: typeof LayoutCompetitionsRoute
  LayoutContestsRoute: typeof LayoutContestsRoute
  LayoutCountriesRoute: typeof LayoutCountriesRoute
  LayoutJudokasRoute: typeof LayoutJudokasRoute
  LayoutRatingChangesRoute: typeof LayoutRatingChangesRoute
  LayoutRatingFormulasRoute: typeof LayoutRatingFormulasRoute
  LayoutRatingsRoute: typeof LayoutRatingsRoute
  LayoutSettingsRoute: typeof LayoutSettingsRoute
  LayoutSyncsRoute: typeof LayoutSyncsRoute
  LayoutIndexRoute: typeof LayoutIndexRoute
}

const LayoutRouteChildren: LayoutRouteChildren = {
  LayoutCommandsRoute: LayoutCommandsRoute,
  LayoutCompetitionsRoute: LayoutCompetitionsRoute,
  LayoutContestsRoute: LayoutContestsRoute,
  LayoutCountriesRoute: LayoutCountriesRoute,
  LayoutJudokasRoute: LayoutJudokasRoute,
  LayoutRatingChangesRoute: LayoutRatingChangesRoute,
  LayoutRatingFormulasRoute: LayoutRatingFormulasRoute,
  LayoutRatingsRoute: LayoutRatingsRoute,
  LayoutSettingsRoute: LayoutSettingsRoute,
  LayoutSyncsRoute: LayoutSyncsRoute,
  LayoutIndexRoute: LayoutIndexRoute,
}

const LayoutRouteWithChildren =
  LayoutRoute._addFileChildren(LayoutRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  LayoutRoute: LayoutRouteWithChildren,
  LoginRoute: LoginRoute,
  RecoverPasswordRoute: RecoverPasswordRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SignupRoute: SignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
